# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 019c075a47e845c03d1d2b306b393d684163e9cc8b2d01b09c03bac94782e7bd90269071fb47720af57a9ca6fb225190e1780d791cd1e5932175fd867e804939

test:
  secret_key_base: 4eb66d2f81a20eb76f0ee3ed7edbb6395fdea3e566e9262fc7e30a360c4b13ac5e13580df754222fd50d50a4172d9272a3b638e925f8c9eda545244842e31caa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
